name: Moje testicky

on: [Push]

jobs:
  build:
    runs-on: docker
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      uses: actions/checkout@v3

      name: Nastav python
      uses: action/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

      name: Nainstaluj zavislost
      run: |
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirments.txt

      name: Otestuj mi kod pytestem
      run: pytest -cov
      # ted udelejte test_app.py a napiset  asserci ktera neprojde

  
